### PR TITLE
// NON-MODULAR CHANGES: Felinid Replacement

### PR DESCRIPTION
**Pull request by TheBonded**
## About The Pull Request
image

TODO

- [ ] Make humans able to select cat ears and tail
- [ ] Add a checkbox that makes them nonhuman to do so
- [ ] make them work with laserpointers/other isfelinid() checks
- [ ] port tarajans

## How does it improve JollyStation
It adds something Jolly wants added

## Changelog

:cl: Bondismyname but I wish it wasnt
add: I will update this when the code is more written
/:cl:

### CODE REVIEW

**Review by Jolly-66 — COMMENTED** [review]
I'm putting this here for the future when you return to this:

You need to make sure you denote any non-modular changes with the following:

`// NON-MODULAR CHANGES: Felinid Replacement`

You need the non-modular comment, but what you put after is on you. Just make sure its descriptive so we know which PR its from.

**Comment by Jolly-66** [comment]
The review was for the code comments, not your PR title.

**Comment by TheBonded** [comment]
> The review was for the code comments, not your PR title.

well im going to pretend like that was entirely intentional and not change it back

its still techincally right

**Comment by Jolly-66** [comment]
Rest in peace dude.

**Comment by Jolly-66** [comment]
No longer needed, as #1859 was merged.

May you rest in peace, Bonded.

**Pull request closed without merging**
