### PR TITLE
Removes Felinids from the game. Tajarans are now the ultimate cat species. Humans now seen with cat ears and tails. What the hell has gone wrong with this PR.

### PR DESCRIPTION
**Pull request by Jolly-66**
Adds Tajarans as a species, as well as removing felinids from being a selectable species.
Ports the sprites from Skyrat.

closes:#621

## Changelog

:cl: Jolly, Bondismyname but I wish it wasnt (posthumous)
add: Tajarans are now a playable species!
del: Felinids are no longer a playable species.
fix: Unique roundstart species should look different again.
qol: Humans can now "become felinids". They have pref options to choose tails and ears.
/:cl:

### CODE REVIEW

**Comment by prodirus** [comment]
image

**Comment by Jolly-66** [comment]
DNM until #1942 is merged and I properly convert this hell over.

**Comment by prodirus** [comment]
There's a bunch of minor stuff that touches things like jellypeople/skrell too. Might be worth mentioning it in your PR description/changelog.

**Comment by prodirus** [comment]
Other than that I think its good to go.

**Comment by Jolly-66** [comment]
> There's a bunch of minor stuff that touches things like jellypeople/skrell too. Might be worth mentioning it in your PR description/changelog.

The changes are noted, as currently the species preview icons are not correct. I just slotted in `update_limb_data` to the proc, which rectifies the preview issue.

**Comment by prodirus** [comment]
time to break everything

**Pull request merged**
